"""add role column to user

Revision ID: 3b9b0e14259e
Revises: f3c58b6e3178
Create Date: 2025-08-18 15:11:41.995382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9b0e14259e'
down_revision = 'f3c58b6e3178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default="user"))

    conn = op.get_bind()
    conn.execute(sa.text("UPDATE \"user\" SET role = 'admin' WHERE is_admin = 1"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default="0"))

    conn = op.get_bind()
    conn.execute(sa.text("UPDATE \"user\" SET is_admin = 1 WHERE role = 'admin'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
