"""Add title column to post

Revision ID: 87770a090044
Revises: 36c4d3e00263
Create Date: 2025-08-13 15:27:35.492194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87770a090044'
down_revision = '36c4d3e00263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
